apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: clustermanagers.operator.open-cluster-management.io
spec:
  group: operator.open-cluster-management.io
  names:
    kind: ClusterManager
    listKind: ClusterManagerList
    plural: clustermanagers
    singular: clustermanager
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ClusterManager configures the controllers on the hub that govern
        registration and work distribution for attached Klusterlets. ClusterManager
        will only be deployed in open-cluster-management-hub namespace.
      type: object
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Spec represents a desired deployment configuration of controllers
            that govern registration and work distribution for attached Klusterlets.
          type: object
          properties:
            registrationImagePullSpec:
              description: RegistrationImagePullSpec represents the desired image
                of registration controller/webhook installed on hub.
              type: string
            workImagePullSpec:
              description: WorkImagePullSpec represents the desired image configuration
                of work controller/webhook installed on hub.
              type: string
        status:
          description: Status represents the current status of controllers that govern
            the lifecycle of managed clusters.
          type: object
          properties:
            conditions:
              description: 'Conditions contain the different condition statuses for
                this ClusterManager. Valid condition types are: Applied: Components
                in hub are applied. Available: Components in hub are available and
                ready to serve. Progressing: Components in hub are in a transitioning
                state. Degraded: Components in hub do not match the desired configuration
                and only provide degraded service.'
              type: array
              items:
                description: StatusCondition contains condition information.
                type: object
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime is the last time the condition
                      changed from one status to another.
                    type: string
                    format: date-time
                  message:
                    description: Message is a human-readable message indicating details
                      about the last status change.
                    type: string
                  reason:
                    description: Reason is a brief reason for the condition's last
                      status change.
                    type: string
                  status:
                    description: Status is the status of the condition. Valid values
                      are True, False, or Unknown.
                    type: string
                  type:
                    description: Type is the type of the cluster condition.
                    type: string
            generations:
              description: Generations are used to determine when an item needs to
                be reconciled or has changed in a way that needs a reaction.
              type: array
              items:
                description: GenerationStatus keeps track of the generation for a
                  given resource so that decisions about forced updates can be made.
                  The definition matches the GenerationStatus defined in github.com/openshift/api/v1.
                type: object
                properties:
                  group:
                    description: The group value is the group of the resource that
                      you're tracking.
                    type: string
                  lastGeneration:
                    description: The lastGeneration value is the last generation of
                      the thing that the controller applies.
                    type: integer
                    format: int64
                  name:
                    description: The name value is the name of the resource that you're
                      tracking.
                    type: string
                  namespace:
                    description: The namespace value is the location of the resource
                      that you're tracking.
                    type: string
                  resource:
                    description: The resource value is the resource type of the resource
                      that you're tracking.
                    type: string
                  version:
                    description: The version value is the version of the resource
                      that you're tracking.
                    type: string
            observedGeneration:
              description: ObservedGeneration is the last generation change.
              type: integer
              format: int64
            relatedResources:
              description: RelatedResources are used to track the resources that are
                related to this ClusterManager.
              type: array
              items:
                description: RelatedResourceMeta represents the resource that is managed
                  by an operator.
                type: object
                properties:
                  group:
                    description: The group value is the group of the resource that
                      you're tracking.
                    type: string
                  name:
                    description: The name value is the name of the resource that you're
                      tracking.
                    type: string
                  namespace:
                    description: The namespace value is the location of the resource
                      that you're tracking.
                    type: string
                  resource:
                    description: The resource value is the resource type of the resource
                      that you're tracking.
                    type: string
                  version:
                    description: The version value is the version of the resource
                      that you're tracking.
                    type: string
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  preserveUnknownFields: false
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
